---
title: "R Tutorial 1"
author: "Alanis S. Mulero Burgos"
date: "`r format(Sys.time(), '%Y-%b-%d, %I:%M %p')`"
output: 
 prettydoc::html_pretty:
   theme: architect
   highlight: github
---

### Pregunta 1 
Crea un objeto llamado height con el valor 175

```{r}
Altura <- 175
```

### Pregunta 2
Calcula el resultado de 25 * 4 - 10

```{r}
25*4-10
```

### Pregunta 3
Usa la función sqrt() para calcular la raíz cuadrada de 81

```{r}
sqrt(81)
```

### Pregunta 4
Asigna la frase “R is fun!” a un objeto llamado message

```{r}
message <- "R is fun"
message
```

### Pregunta 5
Crea dos objetos a <- 10 y b <- 5. Calcula su suma y guárdala en c.

```{r}
a <- 10
b <- 5
c <- (a+b)
c
```

### Pregunta 6
Verifica si 15 es mayor que 20

```{r}
15>20
```

### Pregunta 7
Verifica la clase del objeto "Hello World"

```{r}
obj1 <- ('Hello World')
class(obj1)
```

### Pregunta 8
Run the following code chunk:
- Observe the warnings that appear. (Observa las advertencias que aparecen.)
- Modify the chunk options to suppress warnings without changing the code itself. (Modifica las opciones del chunk para apagar la advertencia sin cambiar el código.)


```{r, warning=F}
log(-1)
```

### Pregunta 9
Run the following code chunk: - Observe the messages that appear. (Observa los mensajes que aparecen.)

Modify the chunk options to suppress messages without changing the code itself. (Modifica las opciones del chunk para apagar mensajes sin cambiar el código.)

```{r}

```

### Pregunta 10

```{r}

```

